1:
1:[IDENTIFICATION][DIVISION][DOT]
2:[COMMENT: =================================================================]
3:[PROGRAM-ID][DOT][ID:CALLMSG][DOT]
4:[AUTHOR][DOT][ID:XXXXXXXXX][DOT]
5:[DATE-WRITTEN][DOT](2008)[DOT]
7:[COMMENT: REMARKS.                   ]
8:[COMMENT: ]
9:[COMMENT:  Programme demo ROUTINE]
10:[COMMENT: ]
11:[COMMENT: ]
12:[ENVIRONMENT][DIVISION][DOT]
13:[COMMENT: =================================================================]
15:[DATA][DIVISION][DOT]
16:[COMMENT: =================================================================]
18:[WORKING-STORAGE][SECTION][DOT]
19:[COMMENT: ------------------------]
21:[LINKAGE][SECTION][DOT]
22:[COMMENT: ----------------]
23:[COPY][ID:MSGZONE][DOT]
24:[COMMENT: ]
25:[PROCEDURE][DIVISION][USING][ID:MSG-ZONE][DOT]
26:[COMMENT: =================================================================]
28:[EVALUATE][ID:MSG-NO]
29:[WHEN]("0001")
30:[MOVE]("Problem BATCH")[TO][ID:MSG-TEXT]
31:[WHEN]("0002")
32:[MOVE]("Forbidden PFKey")[TO][ID:MSG-TEXT]
33:[WHEN]("0003")
34:[MOVE]("Record not found")[TO][ID:MSG-TEXT]
35:[WHEN]("0004")
36:[MOVE]("Mandatory field")[TO][ID:MSG-TEXT]
37:[END-EVALUATE]
39:[GOBACK][DOT]