1:
1:(01)[ID:TUA-ZONE][DOT]
2:(05)[ID:TUA-I-TRAVAIL][DOT]
3:(10)[ID:TUA-I-DTJOUR][PIC][ID:S9][LEFT_BRACKET](8)[RIGHT_BRACKET][COMP-3][DOT]
4:(10)[ID:TUA-I-DTJOURF][PIC][ID:X][LEFT_BRACKET](8)[RIGHT_BRACKET][DOT]